builds:
  - binary: gas
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
  -
    wrap_in_directory: true
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

brews:
  -
    github:
      owner: leighmcculloch
      name: gas
    folder: Formula
    homepage: "https://4d63.com/gas"
    description: Check the state of all your git worktrees.
    test: |
      system "#{bin}/gas -help"
    install: |
      bin.install "gas"
