builds:
  - binary: gal
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386

archive:
  wrap_in_directory: true
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
